# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ProfileEdit

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build ProfileEdit/ProfileEdit/ProfileEdit.csproj
      
    - name: Run
      run: dotnet run ${{ github.event.issue.title }} ${{ github.event.issue.user.login }} --project ProfileEdit/ProfileEdit/ProfileEdit.csproj
      
    - name: Commit and push changes
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "${ISSUE_TITLE} by ${ISSUE_AUTHOR}"
        git push
